"""empty message

Revision ID: 058f424aafc5
Revises: 
Create Date: 2021-07-14 15:05:00.439965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "058f424aafc5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_booking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "appointments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(length=8), nullable=True),
        sa.Column("time", sa.String(length=5), nullable=True),
        sa.Column("doctName", sa.String(length=55), nullable=True),
        sa.Column("doctSpeciality", sa.String(length=55), nullable=True),
        sa.Column("doctIdentity", sa.String(length=128), nullable=True),
        sa.Column("doctAddress", sa.String(length=128), nullable=True),
        sa.Column("beneficiaryName", sa.String(length=55), nullable=True),
        sa.Column("beneficiaryPhone", sa.String(length=12), nullable=True),
        sa.Column("beneficiaryNif", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_booking():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("appointments")
    # ### end Alembic commands ###


def upgrade_profiles():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "beneficiary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=55), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("phone", sa.String(length=55), nullable=True),
        sa.Column("nif", sa.String(length=55), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"], use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "country",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "doctor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=55), nullable=True),
        sa.Column("phone", sa.String(length=12), nullable=True),
        sa.Column("nif", sa.String(length=55), nullable=True),
        sa.Column("photo", sa.String(length=128), nullable=True),
        sa.Column("mode", sa.String(length=55), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "speciality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=55), nullable=False),
        sa.Column("details", sa.Text(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
    )
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("road", sa.String(length=128), nullable=True),
        sa.Column("flat", sa.String(length=55), nullable=True),
        sa.Column("zipcode", sa.String(length=9), nullable=True),
        sa.Column("city", sa.String(length=55), nullable=True),
        sa.Column("country_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doctor_speciality",
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("speciality_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["speciality_id"],
            ["speciality.id"],
        ),
        sa.PrimaryKeyConstraint("doctor_id", "speciality_id"),
    )
    op.create_table(
        "license",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=True),
        sa.Column("issue_date", sa.String(length=8), nullable=True),
        sa.Column("valid_date", sa.String(length=8), nullable=True),
        sa.Column("issuer", sa.String(length=128), nullable=True),
        sa.Column("country", sa.Integer(), nullable=True),
        sa.Column("certificate", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(
            ["country"],
            ["country.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "doctor_license",
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("license_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor.id"],
        ),
        sa.ForeignKeyConstraint(
            ["license_id"],
            ["license.id"],
        ),
        sa.PrimaryKeyConstraint("doctor_id", "license_id"),
    )
    op.create_table(
        "doctor_morada",
        sa.Column("doctor_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["address.id"],
        ),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctor.id"],
        ),
        sa.PrimaryKeyConstraint("doctor_id", "address_id"),
    )
    # ### end Alembic commands ###


def downgrade_profiles():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doctor_morada")
    op.drop_table("doctor_license")
    op.drop_table("license")
    op.drop_table("doctor_speciality")
    op.drop_table("address")
    op.drop_table("speciality")
    op.drop_table("doctor")
    op.drop_table("country")
    op.drop_table("beneficiary")
    # ### end Alembic commands ###


def upgrade_schedules():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.String(length=11), nullable=True),
        sa.Column("time", sa.String(length=11), nullable=True),
        sa.Column("week", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("doctor_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade_schedules():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule")
    # ### end Alembic commands ###
